### ISSUE TITLE
Moving this crate under mina-rs workspace

### ISSUE THREAD

**Issue by creativcoder** [ChainSafe/serde-bin-prot#23]
It would be good to co-locate `serde-bin-prot` crate under mina-rs workspace. Additionally, we can rename it to just `bin-prot` as Rust serialization libraries usually come with serde support within, so having a serde prefix is redundant. Also, the name bin-prot is available on crates.io it we plan to release it in future.

**Comment by willemolding** [comment]
Definitely agree with the rename to `bin-prot`. 

Not sure about it moving to the Mina-rs repo though. Especially if we are going to add a github action for publishing to crates.io and such. It would be nice to keep all of that out of our other repo. Same goes for any issues that third party users might have. Better to have them all here unrelated to Mina

**Comment by creativcoder** [comment]
Cool, i'll proceed with the rename.

My thoughts on moving it was that: As a serialization format, the bin-prot spec is not language agnostic spec (some of the types are not applicable to other languages, let's say Python) at present and thus the library isn't generic enough. The only place we'll find its use is on ocaml <-> rust projects.

Sure, let's keep it here for now, and hope the spec gets updated to be language agnostic in future.
